### ISSUE TITLE
Holy Shield not reading

### ISSUE THREAD

**Issue by antipatheia** [MartinKuschnik/FFXIV-Zodiac-Glass#13]
So, I really don't know a lot about this, but the overlay isn't reading my shield.

![zodiacglass001](https://cloud.githubusercontent.com/assets/17920969/13896627/2d6b7b00-ed58-11e5-9674-ccaa23eaa0fb.PNG)

In [Zodiac Glass/FFXIV/FFXIVItemSet.cs](https://github.com/MartinKuschnik/FFXIV-Zodiac-Glass/blob/master/Zodiac%20Glass/FFXIV/FFXIVItemSet.cs) I see the FieldOffset is 72 for the offhand, but the pointer is showing 40, which is 64 in decimal.

![ce65_0002](https://cloud.githubusercontent.com/assets/17920969/13896621/0d5e3604-ed58-11e5-9b37-d34c1d718c0b.PNG)

I don't know if that's relevant, but after poking around the different files, that's all I'm seeing that could maybe be my issue.

**Comment by MartinKuschnik** [comment]
I think that will be the issue. 
Very smart that you found it!
I suspect that SQ changed the size of FFXIVWeapon struct.
I also calculated 0x40 by using the screenshot like you. 
Try to change the offset and see whether it works.

**Comment by MartinKuschnik** [comment]
I have to make a new release now. I'm not sure when i have the time to do that.

**Comment by antipatheia** [comment]
So, since this isn't my forté, I kind of guess from the coding that it was something I could build/test in Visual Studio Express, and it shows my shield now.

![zodiacglass002](https://cloud.githubusercontent.com/assets/17920969/13902903/13f8e0ee-ee26-11e5-8091-d744cf6cd21c.PNG)

So, fixing that offset helped.

**Comment by MartinKuschnik** [comment]
Release [v1.4.1603.20001](https://github.com/MartinKuschnik/FFXIV-Zodiac-Glass/releases/tag/v1.4.1603.20001) is ready to use.
