### ISSUE TITLE
memmap update

### ISSUE THREAD

**Issue by Pesmare** [MartinKuschnik/FFXIV-Zodiac-Glass#7]
3.1 broke this. Are you able to update this?

Love the tool btw!

**Comment by MartinKuschnik** [comment]
It's hard to do that because i don't have an active subscription right now.

**Comment by MartinKuschnik** [comment]
I updated the addresses by using a trail account.
I'm not absolute sure that it's working now.
Please test it and give me some feedback.

**Comment by Pesmare** [comment]
This looks to be updated and working! Thank you so much! Is there somewhere I can donate or something, for your hard work?

**Comment by MartinKuschnik** [comment]
Thanks for the feedback.

Yes, you can donate by clicking on the Donate entry on the context menu.

![donate](https://cloud.githubusercontent.com/assets/2582960/11170411/a4029ce4-8bd3-11e5-954a-fa42df0af4e0.png)
