### ISSUE TITLE
Patch 3.15

### ISSUE THREAD

**Issue by r4nm4** [MartinKuschnik/FFXIV-Zodiac-Glass#9]
Dear Martin,
can I ask you please, if you may update your amazing project with the new memory address for 3.15 patch? Thank you so much.

**Comment by MartinKuschnik** [comment]
I will give my best.
The problem is that i don't have an active subscription.
I will ask a friend whether i can use his account for doing that.

**Comment by r4nm4** [comment]
Hi! First of all thank you so much for your very quickly answer.
No worries! Im sure about that :) Take your time!
Thanks again!

**Comment by MartinKuschnik** [comment]
Does it work now?

**Comment by r4nm4** [comment]
Wow... so fast! Thank you!
I'm sorry for my delay answer, but we have 10 hours of timezone difference.
I just tried and unfortunately I think this application (maybe you wrote and I didn't read... my bad) works only for Paladin.
My Blm Stardust Rod Novus is not supported.
Thank you so much anyway.

**Comment by MartinKuschnik** [comment]
Sorry, I did a mistake. Does it work now?

**Comment by r4nm4** [comment]
Hi, no worries, I'm a developer too :)
Today I have done with my Nexus therefore I need to wait Zodiac to try again your tool.
I just tried with Nexus and I have the same issue. But I think because I don't need lights.
Thank you for your hard work and please don't worries :)
Take your time.

**Comment by MartinKuschnik** [comment]
Ok, would be nice if you could give me feedback if you have the right weapon.

**Comment by r4nm4** [comment]
Sure! I will try soon I can when I will be Zodiac.
Thank you again!

**Comment by r4nm4** [comment]
Sure! I will try soon I can when I will have Zodiac.
Thank you again!

**Comment by r4nm4** [comment]
It works! Thank you so much!
